ARG ARCH=frommakefile
ARG DOCKERSRC=frommakefile
ARG USERNAME=frommakefile
#
FROM ${USERNAME}/${DOCKERSRC}:${ARCH}
#
ARG PUID=1001
ARG PGID=1001
ARG JNVERSION=latest
#
ENV LANG=C.UTF-8 \
    FC_LANG=en-US \
    LC_CTYPE=en_US.UTF-8 \
    JENKINS_HOME=/var/jenkins_home \
    JENKINS_SLAVE_AGENT_PORT=50000 \
    JENKINS_UC=https://updates.jenkins.io \
    JENKINS_UC_EXPERIMENTAL=https://updates.jenkins.io/experimental \
    COPY_REFERENCE_FILE_LOG=/var/jenkins_home/copy_reference_file.log
#
COPY root/ /
#
RUN set -xe \
    && addgroup -g ${PGID} -S jenkins \
    && adduser -u ${PUID} -G jenkins -h /var/jenkins_home -s /bin/bash -D jenkins \
    && apk add --no-cache --purge -Uu ca-certificates git sudo shadow openjdk8-jre fontconfig openssh-client curl unzip ttf-dejavu coreutils \
#    && mkdir -p /usr/share/jenkins/ref/init.groovy.d \ # done inside root/
    && curl -o /usr/share/jenkins/jenkins.war -jkSL http://mirrors.jenkins.io/war-stable/${JNVERSION}/jenkins.war \
    && echo 'jenkins ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers \
    && rm -rf /var/cache/apk/* /tmp/*
#
ENV JAVA_HOME /usr/lib/jvm/java-1.8-openjdk
RUN chown -R jenkins:jenkins /var/jenkins_home /usr/share/jenkins
#
EXPOSE 8080 50000
#
ENTRYPOINT ["/init"]
